_target_: experiments.amplitudes.wrappers.LGATrWrapper
particle_type: null
network_float64: null

net:
 _target_: lgatr.LGATr

 in_mv_channels: 1
 in_s_channels: null
 out_mv_channels: 1
 out_s_channels: null
 hidden_mv_channels: 20
 hidden_s_channels: 32
 
 num_blocks: 8
 attention:
  num_heads: 8
  multi_query: false
 mlp:
  activation: gelu

defaults:
 - framesnet: identity
