_target_: experiments.amplitudes.wrappers.GraphNetWrapper
particle_type: null
include_nodes: true
include_edges: true
network_float64: null

net:
 _target_: lloca.backbone.graphnet.GraphNet

 in_channels: null
 hidden_reps: "64x0n+16x1n"
 out_channels: 1
 num_edge_attr: null

 num_blocks: 3
 num_layers_mlp1: 3
 num_layers_mlp2: 0

defaults:
 - framesnet: identity
