_target_: experiments.eventgen.wrappers.GraphNetCFM
include_edges: false

net:
 _target_: lloca.backbone.graphnet.GraphNet

 in_channels: null
 out_channels: null
 hidden_reps: "64x0n+16x1n"
 num_edge_attr: null
 
 num_blocks: 3
 num_layers_mlp1: 3
 num_layers_mlp2: 0

defaults:
 - framesnet: identity
