_target_: experiments.eventgen.wrappers.LGATrCFM

net:
 _target_: lgatr.LGATr

 in_mv_channels: null
 in_s_channels: null
 out_mv_channels: 1
 out_s_channels: null
 hidden_mv_channels: 16
 hidden_s_channels: 32

 num_blocks: 6
 attention:
  num_heads: 8
  multi_query: false
 mlp:
  activation: gelu

defaults:
 - framesnet: identity