_target_: experiments.tagging.wrappers.PELICANWrapper
out_channels: null

net:
 _target_: experiments.baselines.pelican.pelican.PELICAN
 _partial_: true

 num_scalars: null
 num_channels_1: 132
 num_channels_2: 78
 
defaults:
 - framesnet: identity
