_target_: experiments.tagging.wrappers.TransformerWrapper
in_channels: null
out_channels: null
use_amp: false
add_fourmomenta_backbone: false
mean_aggregation: true

net:
 _target_: lloca.backbone.transformer.Transformer
 _partial_: true

 in_channels: null
 attn_reps: "12x0n+1x1n" # reps can be varied, but number of channels should stay fixed
 out_channels: null

 num_blocks: 12
 num_heads: 8
 mlp_factor: 2
 dropout_prob: null
 checkpoint_blocks: false

defaults:
 - framesnet: identity
