_target_: experiments.tagging.wrappers.TransformerWrapper
in_channels: null
out_channels: null
use_amp: false
attention_backend: xformers
add_fourmomenta_backbone: false
mean_aggregation: true

net:
 _target_: lloca.backbone.transformer.Transformer
 _partial_: true

 in_channels: null
 attn_reps: "4x0n+2x1n" # reps can be varied, but number of channels should stay fixed
 out_channels: null

 num_blocks: 2
 num_heads: 4
 mlp_factor: 1
 dropout_prob: null
 checkpoint_blocks: false

defaults:
 - framesnet: identity
