_target_: experiments.tagging.wrappers.PELICANWrapperOfficial
out_channels: null

net:
 _target_: experiments.baselines.pelican.pelican.PELICANOfficial
 _partial_: true

 num_scalars: null
 num_channels_1: 132
 num_channels_2: 78

defaults:
 - framesnet: identity
