_target_: experiments.tagging.wrappers.LoTrWrapper
mean_aggregation: false
out_channels: null
use_amp: false
attention_backend: xformers

net:
 _target_: experiments.baselines.lorentztransformer.LorentzTransformer
 _partial_: true

 in_v_channels: 1
 in_s_channels: null
 out_v_channels: 0
 out_s_channels: null
 hidden_v_channels: 32
 hidden_s_channels: 64

 num_blocks: 12
 num_heads: 8
 mlp_ratio: 2
 attn_ratio: 2
 mix_linear: false
 compile: true

defaults:
 - framesnet: identity
