# PELICAN architecture allowing for fair comparison (similar memory and timing)
# with the typical 200k-parameter LorentzNet and ParticleNet graph networks.
# The original PELICAN also has 200k parameters, but uses `factorize=true`
# and therefore has the same memory and timing cost as a 800k parameter network.
_target_: experiments.tagging.wrappers.PELICANWrapper
out_channels: null

net:
 _target_: pelican.nets.PELICAN
 _partial_: true

 in_channels_rank0: 0
 in_channels_rank1: null
 in_channels_rank2: 1
 out_rank: 0
 out_channels: 1

 num_blocks: 5
 hidden_channels: 72
 increase_hidden_channels: 0.59

 map_multipliers: true
 factorize: false
 activation: leaky_relu
 aggr: mean
 compile: true
 checkpoint_blocks: false

defaults:
 - framesnet: identity
