iterations: 200000
batchsize: 2048

optimizer: AdamW
betas: [.9, .999]
eps: 1e-8
weight_decay: 0

lr_factor_framesnet: 1
weight_decay_framesnet: 0

lr: 1e-3
scheduler: ReduceLROnPlateau
scheduler_scale: 1
cosanneal_eta_min: 0
reduceplateau_factor: 0.1
reduceplateau_patience: 20
onecycle_max_lr: 10
onecycle_pct_start: 0.3

es_patience: 50
es_load_best_model: true

log_every_n_steps: 1000
validate_every_n_steps: 1000
validate_every_n_epochs_min: null

log_grad_norm: true
clip_grad_norm_framesnet: null
clip_grad_norm: 5
clip_grad_value: null
max_grad_norm: null
