# hyperparameters from https://arxiv.org/pdf/2407.08682 section III
# I didnt manage to reproduce the published metrics with this setup
batchsize: 256
weight_decay: 0.01
iterations: 72000 # 15 epochs
validate_every_n_steps: 4800 # after each epoch

defaults:
 - top_ParT
