# hyperparameters from https://arxiv.org/abs/2202.03772 section 5.1 and 5.2
# alternatively https://github.com/jet-universe/particle_transformer/blob/main/train_TopLandscape.sh
batchsize: 512
lr: 1e-3
weight_decay: 0.01
iterations: 48000 # 20 epochs
validate_every_n_steps: 2400 # after each epoch
optimizer: Ranger
scheduler: flat+decay

defaults:
 - tag_default
