exp_type: amplitudesxl
exp_name: ampxl

data:
 dataset: zgggg_0
 data_path : data/zgggg_xl  # /remote/gpu02/breso/lorentz-gatr/data/zgggg_1000M
 train_test_val: [.4, .5, .1]
 num_train_files: 100
 num_prefetch: 2

evaluation:
 eval_set: [test, val]

defaults:
 - amplitudes
 - _self_