exp_name: ???
exp_type: ???
run_name: null
base_dir: .

jobid: null
seed: null
debug: false
use_float64: false
float32_matmul_precision: highest

parq:
 use: false
 bits: 0
 quantizer: lsbq

 prox_map: parq
 start_step: 0
 final_hard_steps: 0
 steepness: 100

 inout: false
 attn: true
 mlp: true
 bias: false

 warmup_steps: 0
 quant_period: 10
 quant_per_channel: false
 quant_shrink: false
 anneal_wd_frac: 0.0
 nm_gamma: 0.0

inputquant:
 use: false
 bits: 8
 quantizer: uniform
 mlp: true
 attn: true
 dim: null
 quantize_output: true

warm_start_idx: null
save: true
use_mlflow: false
save_source: true
ema: false
ema_decay: 0.999

train: true
evaluate: true
evaluation:
 batchsize: 1024

plot: true
plotting:
 loss: true

mlflow:
 db: '${base_dir}/runs/${exp_name}/mlflow/mlflow.db'
 artifacts: '${base_dir}/runs/${exp_name}/mlflow/artifacts'

defaults:
 - hydra
 - _self_