_target_: lloca.framesnet.equi_frames.LearnedPDFrames
is_global: false
random: false
fix_params: false
gamma_max: null
gamma_hardness: 10
deterministic_boost: null
compile: false
ortho_kwargs:
 use_float64: true
 method: gramschmidt
 eps_norm: 1e-15
 eps_reg: 1e-16
 eps_reg_lightlike: 1e-16
 checks: false

defaults:
 - equivectors: equimlp
